add schema init

diff --git a/bin/docker-entrypoint b/bin/docker-entrypoint
--- a/bin/docker-entrypoint
+++ b/bin/docker-entrypoint
@@ -1,13 +1,13 @@
 #!/bin/bash
-cd /var/www/html
+#cd /var/www/html
 
 HOST=$(hostname)
 APP_NAME="tt-rss"
 
 # TT-RSS Config
-TTRSS_DIR="$APP_NAME"
-DEFAULT_CONF="$TTRSS_DIR/config.php-dist"
-CONF="$TTRSS_DIR/config.php"
+TTRSS_DIRNAME="$APP_NAME"
+DEFAULT_CONF="$TTRSS_DIRNAME/config.php-dist"
+CONF="$TTRSS_DIRNAME/config.php"
 
 # Nginx Config
 NGINX_CFG_DIR="/external/nginx_conf"
@@ -24,23 +24,22 @@ LOCAL_PORT="80"
 LOCAL_URI="$APP_NAME"
 
 install_ttrss() {
-	if [[ -d "$TTRSS_DIR" ]]; then
+	if [[ -d "$TTRSS_DIRNAME" ]]; then
 		printf "\n[INSTALL] tt-rss already installed." "$TTRSS_TAG"
 		# TODO : think about updating ?
 		return 0
 	else
-		if [[ -d "/ttrss_${TTRSS_TAG}" ]]; then
+		if mv "/ttrss_${TTRSS_TAG}" "$TTRSS_DIRNAME" ; then
 			printf "\n[INSTALL] Using default tt-rss version (%s)." "$TTRSS_TAG"
-			mv "/ttrss_${TTRSS_TAG}" "$TTRSS_DIR"
 		else
 			printf "\n[INSTALL] Downloading tt-rss version %s." "$TTRSS_TAG"
-			#[[ -z "$TTRSS_TAG" ]] && TTRSS_TAG="master"
+			# rm default install
 			rm -rf "/ttrss_*"
-			git clone -b "$TTRSS_TAG" "$TTRSS_REPO" "$TTRSS_DIR"
+			git clone -b "$TTRSS_TAG" "$TTRSS_REPO" "$TTRSS_DIRNAME"
 		fi
 		if [[ -f "$DEFAULT_CONF" ]] ; then
-			chown -R www-data:www-data "$TTRSS_DIR"
-			printf "\n[INSTALL] TT-RSS.$TAG is installed in %s" "$(pwd)/$TTRSS_DIR"
+			chown -R www-data:www-data "$TTRSS_DIRNAME"
+			printf "\n[INSTALL] TT-RSS.$TAG is installed in %s" "$(pwd)/$TTRSS_DIRNAME"
 			return 0
 		fi
 		return 1
@@ -130,6 +129,14 @@ write_sql_init() {
 	fi
 }
 
+init_schema() {
+	if ! php /init_schema.php -ttrss_path "$(pwd)/$TTRSS_DIRNAME" ; then
+		printf "\nError during schema initialization!\n"
+		return 1
+	fi
+	printf "\nDatabase initialized with tt-rss schema.\n"
+}
+
 write_nginx_proxyconf() {
 	setProxyConf "tt-rss" "$NGINX_CFG_FILE" "$LOCAL_PROTOCOL://$LOCAL_DOMAIN:$LOCAL_PORT/$LOCAL_URI" "$SELF_URL_PATH"
 }
@@ -169,6 +176,8 @@ wait_postgres() {
 			exit 1
 		fi
 	done
+	printf "\nPostgres UP!\n"
+	init_schema
 	return 0
 }
 
